In [1]:
# @hidden_cell
# The project token is an authorization token that is used to access project resources like data sources, connections, and used by platform APIs.
from project_lib import Project
project = Project(project_id='af42ca1e-8ba7-4d0c-b007-87415cc501b3', project_access_token='p-c505353f7e2b2c471c5bab348c0d53dce3fe6675')
pc = project.project_context

In [2]:
import requests # library to handle requests
import pandas as pd # library for data analsysis
import numpy as np # library to handle data in a vectorized manner
import random # library for random number generation

!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

!conda install -c conda-forge folium=0.5.0 --yes
import folium # plotting library


print('Folium installed')
print('Libraries imported.')

Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python_abi-3.6             |          1_cp36m           4 KB  conda-forge
    geographiclib-1.50         |             py_0          34 KB  conda-forge
    geopy-1.22.0               |     pyh9f0ad1d_0          63 KB  conda-forge
    certifi-2020.4.5.2         |   py36h9f0ad1d_0         152 KB  conda-forge
    ca-certificates-2020.4.5.2 |       hecda079_0         147 KB  conda-forge
    openssl-1.1.1g             |       h516909a_0         2.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.5 MB

The following NEW packages will be INSTALLED:

    geographiclib:   1.50-py_0           conda-forge
    geopy:           1.22.0-pyh9f0ad1d_0 conda-forge
    python_abi:      3.6-1_cp36m         conda-forge

The following packages will be UPDATED:

    ca-certificates: 2020.1.1-0                      --> 2020.4.5.2-hecda079_0     conda-forge
    certifi:         2020.4.5.1-py36_0               --> 2020.4.5.2-py36h9f0ad1d_0 conda-forge
    openssl:         1.1.1g-h7b6447c_0               --> 1.1.1g-h516909a_0         conda-forge


Downloading and Extracting Packages
python_abi-3.6       | 4 KB      | ##################################### | 100%
geographiclib-1.50   | 34 KB     | ##################################### | 100%
geopy-1.22.0         | 63 KB     | ##################################### | 100%
certifi-2020.4.5.2   | 152 KB    | ##################################### | 100%
ca-certificates-2020 | 147 KB    | ##################################### | 100%
openssl-1.1.1g       | 2.1 MB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python36

  added / updated specs:
    - folium=0.5.0


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vincent-0.4.4              |             py_1          28 KB  conda-forge
    folium-0.5.0               |             py_0          45 KB  conda-forge
    branca-0.4.1               |             py_0          26 KB  conda-forge
    altair-4.1.0               |             py_1         614 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         713 KB

The following NEW packages will be INSTALLED:

    altair:  4.1.0-py_1 conda-forge
    branca:  0.4.1-py_0 conda-forge
    folium:  0.5.0-py_0 conda-forge
    vincent: 0.4.4-py_1 conda-forge


Downloading and Extracting Packages
vincent-0.4.4        | 28 KB     | ##################################### | 100%
folium-0.5.0         | 45 KB     | ##################################### | 100%
branca-0.4.1         | 26 KB     | ##################################### | 100%
altair-4.1.0         | 614 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Folium installed
Libraries imported.

In [3]:
from sklearn.cluster import KMeans

In [4]:
website_url = requests.get('https://en.wikipedia.org/wiki/Districts_of_Hong_Kong').text

from bs4 import BeautifulSoup
soup = BeautifulSoup(website_url,'lxml')

data = []
columns = []
table = soup.find(class_='wikitable')
for index, tr in enumerate(table.find_all('tr')):
    section = []
    for td in tr.find_all(['th','td']):
        section.append(td.text.rstrip())
    
   
    if (index == 0):
        columns = section
    else:
        data.append(section)
hk_df = pd.DataFrame(data = data,columns = columns)
hk_df=hk_df.rename(columns={'Population[when?] [6]':'Population'})
hk_df.head()

,District,Chinese,Population,Area(km2),Density(/km2),Region
0,Central and Western,中西區,"244,600",12.44,"19,983.92",Hong Kong Island
1,Eastern,東區,"574,500",18.56,"31,217.67",Hong Kong Island
2,Southern,南區,"269,200",38.85,"6,962.68",Hong Kong Island
3,Wan Chai,灣仔區,"150,900",9.83,"15,300.10",Hong Kong Island
4,Sham Shui Po,深水埗區,"390,600",9.35,"41,529.41",Kowloon

In [5]:
CLIENT_ID = 'LLQBPWSUPKTUQEXLUURK1IKPHZ3SMBWMTB41Z3112OH22LXU' # your Foursquare ID
CLIENT_SECRET = 'Q5QCXRQD2AIUZZ4LGQIHG04C055GABVQFYKFKR2A5CSPULSZ' # your Foursquare Secret
VERSION = '20180604'
LIMIT = 30
print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: LLQBPWSUPKTUQEXLUURK1IKPHZ3SMBWMTB41Z3112OH22LXU
CLIENT_SECRET:Q5QCXRQD2AIUZZ4LGQIHG04C055GABVQFYKFKR2A5CSPULSZ

In [6]:
address = 'Hong Kong'

geolocator = Nominatim(user_agent="foursquare_agent")
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

22.2793278 114.1628131

In [10]:
map_hk = folium.Map(location=[latitude, longitude], zoom_start=10)
map_hk

In [7]:
from geopy.geocoders import Nominatim
geolocator= Nominatim(user_agent="Hong_Kong_explorer")
hk_df['Dist_Lat']=hk_df['District'].apply(geolocator.geocode).apply(lambda x:x.latitude)
hk_df['Dist_Long']=hk_df['District'].apply(geolocator.geocode).apply(lambda x:x.longitude)


hk_df.head(18)

,District,Chinese,Population,Area(km2),Density(/km2),Region,Dist_Lat,Dist_Long
0,Central and Western,中西區,"244,600",12.44,"19,983.92",Hong Kong Island,22.281322,114.160258
1,Eastern,東區,"574,500",18.56,"31,217.67",Hong Kong Island,1.178718,38.602580
2,Southern,南區,"269,200",38.85,"6,962.68",Hong Kong Island,31.990978,-102.071297
3,Wan Chai,灣仔區,"150,900",9.83,"15,300.10",Hong Kong Island,22.279015,114.172483
4,Sham Shui Po,深水埗區,"390,600",9.35,"41,529.41",Kowloon,22.328190,114.160854
5,Kowloon City,九龍城區,"405,400",10.02,"40,194.70",Kowloon,22.330160,114.189937
6,Kwun Tong,觀塘區,"641,100",11.27,"56,779.05",Kowloon,22.312937,114.225610
7,Wong Tai Sin,黃大仙區,"426,200",9.30,"45,645.16",Kowloon,22.341654,114.193859
8,Yau Tsim Mong,油尖旺區,"318,100",6.99,"44,864.09",Kowloon,22.307404,114.165526
9,Islands,離島區,"146,900",175.12,825.14,New Territories,33.838992,-96.759999
10,Kwai Tsing,葵青區,"507,100",23.34,"21,503.86",New Territories,22.341007,114.104285
11,North,北區,"310,800",136.61,"2,220.19",New Territories,64.573154,11.528036
12,Sai Kung,西貢區,"448,600",129.65,"3,460.08",New Territories,22.382249,114.272828
13,Sha Tin,沙田區,"648,200",68.71,"9,433.85",New Territories,22.383557,114.189985
14,Tai Po,大埔區,"307,100",136.15,"2,220.35",New Territories,22.449402,114.171133
15,Tsuen Wan,荃灣區,"303,600",61.71,"4,887.38",New Territories,22.371661,114.113470
16,Tuen Mun,屯門區,"495,900",82.89,"5,889.38",New Territories,22.391216,113.976282
17,Yuen Long,元朗區,"607,200",138.46,"4,297.99",New Territories,22.442646,114.030434

In [178]:
print(hk_df.loc[1,'Dist_Lat'])
hk_df.loc[1,'Dist_Lat']=22.2734
hk_df.loc[1,'Dist_Long']=114.2361
hk_df.loc[11,'Dist_Lat']=22.5009
hk_df.loc[11,'Dist_Long']=114.1558
hk_df.loc[2,'Dist_Lat']=22.2432
hk_df.loc[2,'Dist_Long']=114.1974
hk_df.loc[9,'Dist_Lat']=22.2628
hk_df.loc[9,'Dist_Long']=113.9655

hk_df.head()

22.2734

,District,Chinese,Population,Area(km2),Density(/km2),Region,Dist_Lat,Dist_Long
0,Central and Western,中西區,"244,600",12.44,"19,983.92",Hong Kong Island,22.281322,114.160258
1,Eastern,東區,"574,500",18.56,"31,217.67",Hong Kong Island,22.273400,114.236100
2,Southern,南區,"269,200",38.85,"6,962.68",Hong Kong Island,22.243200,114.197400
3,Wan Chai,灣仔區,"150,900",9.83,"15,300.10",Hong Kong Island,22.279015,114.172483
4,Sham Shui Po,深水埗區,"390,600",9.35,"41,529.41",Kowloon,22.328190,114.160854

In [179]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['District', 
                  'District Latitude', 
                  'District Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [180]:
hk_district_venues = getNearbyVenues(names=hk_df['District'],
                                   latitudes=hk_df['Dist_Lat'],
                                   longitudes=hk_df['Dist_Long']
                                  )

Central and Western
Eastern
Southern
Wan Chai
Sham Shui Po
Kowloon City
Kwun Tong
Wong Tai Sin
Yau Tsim Mong
Islands
Kwai Tsing
North
Sai Kung
Sha Tin
Tai Po
Tsuen Wan
Tuen Mun
Yuen Long

In [181]:
hk_district_onehot = pd.get_dummies(hk_district_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
hk_district_onehot['District'] = hk_district_venues['District'] 

# move neighborhood column to the first column
fixed_columns = [hk_district_onehot.columns[-1]] + list(hk_district_onehot.columns[:-1])
hk_district_onehot = hk_district_onehot[fixed_columns]

hk_district_onehot.head()

,District,American Restaurant,Art Gallery,Asian Restaurant,Astrologer,Athletics & Sports,BBQ Joint,Bakery,Bar,Beijing Restaurant,...,Thai Restaurant,Theme Park,Toy / Game Store,Train Station,Tunnel,Udon Restaurant,Vietnamese Restaurant,Wine Shop,Yunnan Restaurant,Zoo
0,Central and Western,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Central and Western,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Central and Western,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Central and Western,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Central and Western,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [183]:
hk_district_grouped = hk_district_onehot.groupby('District').mean().reset_index()
hk_district_grouped.head()

,District,American Restaurant,Art Gallery,Asian Restaurant,Astrologer,Athletics & Sports,BBQ Joint,Bakery,Bar,Beijing Restaurant,...,Thai Restaurant,Theme Park,Toy / Game Store,Train Station,Tunnel,Udon Restaurant,Vietnamese Restaurant,Wine Shop,Yunnan Restaurant,Zoo
0,Central and Western,0.0,0.0,0.000000,0.0,0.0,0.0,0.033333,0.033333,0.0,...,0.033333,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
1,Eastern,0.0,0.0,0.000000,0.0,0.0,0.0,0.111111,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
2,Islands,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
3,Kowloon City,0.0,0.0,0.033333,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.200000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0
4,Kwai Tsing,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0,...,0.000000,0.0,0.0,0.0,0.333333,0.0,0.0,0.0,0.0,0.0

In [184]:
num_top_venues = 5

for hood in hk_district_grouped['District']:
    print("----"+hood+"----")
    temp = hk_district_grouped[hk_district_grouped['District'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Central and Western----
                venue  freq
0               Hotel  0.10
1              Lounge  0.10
2  Chinese Restaurant  0.07
3   French Restaurant  0.07
4          Steakhouse  0.07


----Eastern----
                  venue  freq
0        Farmers Market  0.11
1                Bakery  0.11
2           Coffee Shop  0.11
3     Convenience Store  0.11
4  Cantonese Restaurant  0.11


----Islands----
                    venue  freq
0          Scenic Lookout   1.0
1     American Restaurant   0.0
2          Lingerie Store   0.0
3     Shanghai Restaurant   0.0
4  Shabu-Shabu Restaurant   0.0


----Kowloon City----
               venue  freq
0    Thai Restaurant  0.20
1       Dessert Shop  0.13
2               Café  0.07
3        Coffee Shop  0.07
4  Hotpot Restaurant  0.07


----Kwai Tsing----
                    venue  freq
0    Taiwanese Restaurant  0.33
1                  Tunnel  0.33
2      Chinese Restaurant  0.33
3                   Plaza  0.00
4  Shabu-Shabu Restaurant  0.00


----Kwun Tong----
                venue  freq
0  Chinese Restaurant  0.13
1      Cha Chaan Teng  0.07
2                Café  0.07
3          Sports Bar  0.03
4                 Gym  0.03


----North----
                    venue  freq
0            Noodle House   0.5
1          History Museum   0.5
2     American Restaurant   0.0
3                   Plaza   0.0
4  Shabu-Shabu Restaurant   0.0


----Sai Kung----
                venue  freq
0  Seafood Restaurant  0.17
1     Thai Restaurant  0.10
2                Café  0.10
3         Pizza Place  0.07
4         Coffee Shop  0.07


----Sha Tin----
                  venue  freq
0  Cantonese Restaurant  0.07
1          Dessert Shop  0.07
2         Shopping Mall  0.07
3        Clothing Store  0.07
4                  Café  0.07


----Sham Shui Po----
                  venue  freq
0          Noodle House  0.27
1    Italian Restaurant  0.07
2  Hong Kong Restaurant  0.07
3         Shopping Mall  0.07
4           Snack Place  0.07


----Southern----
                 venue  freq
0                  Spa  0.25
1   Athletics & Sports  0.25
2          Coffee Shop  0.25
3          Supermarket  0.25
4  American Restaurant  0.00


----Tai Po----
                venue  freq
0        Noodle House  0.14
1  Chinese Restaurant  0.14
2       Shopping Mall  0.09
3    Sushi Restaurant  0.09
4            Bus Stop  0.09


----Tsuen Wan----
              venue  freq
0      Noodle House  0.13
1      Dessert Shop  0.10
2       Coffee Shop  0.10
3    Cha Chaan Teng  0.07
4  Sushi Restaurant  0.07


----Tuen Mun----
                  venue  freq
0         Shopping Mall  0.13
1           Coffee Shop  0.13
2                  Café  0.10
3  Cantonese Restaurant  0.07
4      Department Store  0.07


----Wan Chai----
                  venue  freq
0                 Hotel  0.10
1           Coffee Shop  0.10
2  Cantonese Restaurant  0.07
3    Italian Restaurant  0.07
4   Japanese Restaurant  0.07


----Wong Tai Sin----
                  venue  freq
0                  Park  0.14
1  Fast Food Restaurant  0.14
2           Coffee Shop  0.14
3                Temple  0.07
4   Szechuan Restaurant  0.07


----Yau Tsim Mong----
                venue  freq
0  Chinese Restaurant  0.12
1                Café  0.08
2      Sandwich Place  0.08
3        Dessert Shop  0.08
4   Indian Restaurant  0.08


----Yuen Long----
                  venue  freq
0    Chinese Restaurant  0.20
1          Noodle House  0.13
2  Fast Food Restaurant  0.10
3          Dessert Shop  0.10
4                Market  0.07

In [185]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [186]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['District']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
hk_district_venues_sorted = pd.DataFrame(columns=columns)
hk_district_venues_sorted['District'] = hk_district_grouped['District']

for ind in np.arange(hk_district_grouped.shape[0]):
    hk_district_venues_sorted.iloc[ind, 1:] = return_most_common_venues(hk_district_grouped.iloc[ind, :], num_top_venues)

hk_district_venues_sorted.head(17)

,District,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Central and Western,Hotel,Lounge,Cantonese Restaurant,French Restaurant,Chinese Restaurant,Steakhouse,Cycle Studio,Japanese Restaurant,Gym / Fitness Center,Plaza
1,Eastern,Convenience Store,Bakery,Chinese Restaurant,Paper / Office Supplies Store,Tea Room,Coffee Shop,Pharmacy,Cantonese Restaurant,Farmers Market,Furniture / Home Store
2,Islands,Scenic Lookout,Zoo,Dessert Shop,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant,Flea Market,French Restaurant,Furniture / Home Store
3,Kowloon City,Thai Restaurant,Dessert Shop,Noodle House,Coffee Shop,Hotpot Restaurant,Café,Halal Restaurant,Restaurant,Dim Sum Restaurant,Pastry Shop
4,Kwai Tsing,Tunnel,Chinese Restaurant,Taiwanese Restaurant,Zoo,Gym,Dim Sum Restaurant,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant
5,Kwun Tong,Chinese Restaurant,Cha Chaan Teng,Café,Pizza Place,Restaurant,Department Store,Furniture / Home Store,Paper / Office Supplies Store,Shopping Mall,Coffee Shop
6,North,Noodle House,History Museum,Zoo,Gym / Fitness Center,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant,Flea Market,French Restaurant
7,Sai Kung,Seafood Restaurant,Café,Thai Restaurant,Burger Joint,Pizza Place,Coffee Shop,Dessert Shop,Park,Gastropub,Chinese Restaurant
8,Sha Tin,Dessert Shop,Shopping Mall,Clothing Store,Cantonese Restaurant,Café,Ice Cream Shop,Supermarket,Dumpling Restaurant,Dim Sum Restaurant,Department Store
9,Sham Shui Po,Noodle House,Chinese Restaurant,Italian Restaurant,Snack Place,Café,Shopping Mall,Hong Kong Restaurant,Flea Market,Cha Chaan Teng,Sushi Restaurant
10,Southern,Athletics & Sports,Coffee Shop,Spa,Supermarket,Zoo,German Restaurant,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant
11,Tai Po,Noodle House,Chinese Restaurant,Sushi Restaurant,Bus Stop,Shopping Mall,River,Plaza,Fast Food Restaurant,Coffee Shop,Soup Place
12,Tsuen Wan,Noodle House,Coffee Shop,Dessert Shop,Cha Chaan Teng,Italian Restaurant,Japanese Restaurant,Sushi Restaurant,Buffet,Shopping Mall,Cantonese Restaurant
13,Tuen Mun,Coffee Shop,Shopping Mall,Café,Department Store,Cantonese Restaurant,Zoo,Shanghai Restaurant,Seafood Restaurant,Dessert Shop,Steakhouse
14,Wan Chai,Hotel,Coffee Shop,Cantonese Restaurant,Italian Restaurant,Japanese Restaurant,Electronics Store,Chinese Restaurant,Spanish Restaurant,Clothing Store,Seafood Restaurant
15,Wong Tai Sin,Park,Fast Food Restaurant,Coffee Shop,Hong Kong Restaurant,Market,Szechuan Restaurant,Burger Joint,Temple,Chinese Restaurant,Pool
16,Yau Tsim Mong,Chinese Restaurant,Café,Sandwich Place,Dessert Shop,Indian Restaurant,Shaanxi Restaurant,Market,Park,Clothing Store,Vietnamese Restaurant

In [227]:
# set number of clusters
kclusters = 6
hk_district_grouped_clustering = hk_district_grouped.drop('District', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(hk_district_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([1, 1, 4, 1, 3, 1, 2, 1, 1, 0], dtype=int32)

In [83]:
hk_df.shape

(18, 8)

In [85]:
hk_district_grouped.shape

(18, 107)

In [229]:
# add clustering labels
hk_district_venues_sorted.insert(0,'Cluster-Labels-', kmeans.labels_)

hk_district_merged = hk_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
hk_district_merged = hk_district_merged.join(hk_district_venues_sorted.set_index('District'), on='District')
hk_district_merged.head() # check the last columns

,District,Chinese,Population,Area(km2),Density(/km2),Region,Dist_Lat,Dist_Long,Cluster-Labels-,Cluster-Labels,...,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Central and Western,中西區,"244,600",12.44,"19,983.92",Hong Kong Island,22.281322,114.160258,1,0,...,Hotel,Lounge,Cantonese Restaurant,French Restaurant,Chinese Restaurant,Steakhouse,Cycle Studio,Japanese Restaurant,Gym / Fitness Center,Plaza
1,Eastern,東區,"574,500",18.56,"31,217.67",Hong Kong Island,22.273400,114.236100,1,0,...,Convenience Store,Bakery,Chinese Restaurant,Paper / Office Supplies Store,Tea Room,Coffee Shop,Pharmacy,Cantonese Restaurant,Farmers Market,Furniture / Home Store
2,Southern,南區,"269,200",38.85,"6,962.68",Hong Kong Island,22.243200,114.197400,5,4,...,Athletics & Sports,Coffee Shop,Spa,Supermarket,Zoo,German Restaurant,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant
3,Wan Chai,灣仔區,"150,900",9.83,"15,300.10",Hong Kong Island,22.279015,114.172483,1,0,...,Hotel,Coffee Shop,Cantonese Restaurant,Italian Restaurant,Japanese Restaurant,Electronics Store,Chinese Restaurant,Spanish Restaurant,Clothing Store,Seafood Restaurant
4,Sham Shui Po,深水埗區,"390,600",9.35,"41,529.41",Kowloon,22.328190,114.160854,0,0,...,Noodle House,Chinese Restaurant,Italian Restaurant,Snack Place,Café,Shopping Mall,Hong Kong Restaurant,Flea Market,Cha Chaan Teng,Sushi Restaurant

In [236]:
hk_district_merged.drop('Cluster-Labels-6',axis=1,inplace=True)

In [237]:
hk_district_merged.head(30)

,District,Chinese,Population,Area(km2),Density(/km2),Region,Dist_Lat,Dist_Long,Cluster-Labels-,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Central and Western,中西區,"244,600",12.44,"19,983.92",Hong Kong Island,22.281322,114.160258,1,Hotel,Lounge,Cantonese Restaurant,French Restaurant,Chinese Restaurant,Steakhouse,Cycle Studio,Japanese Restaurant,Gym / Fitness Center,Plaza
1,Eastern,東區,"574,500",18.56,"31,217.67",Hong Kong Island,22.273400,114.236100,1,Convenience Store,Bakery,Chinese Restaurant,Paper / Office Supplies Store,Tea Room,Coffee Shop,Pharmacy,Cantonese Restaurant,Farmers Market,Furniture / Home Store
2,Southern,南區,"269,200",38.85,"6,962.68",Hong Kong Island,22.243200,114.197400,5,Athletics & Sports,Coffee Shop,Spa,Supermarket,Zoo,German Restaurant,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant
3,Wan Chai,灣仔區,"150,900",9.83,"15,300.10",Hong Kong Island,22.279015,114.172483,1,Hotel,Coffee Shop,Cantonese Restaurant,Italian Restaurant,Japanese Restaurant,Electronics Store,Chinese Restaurant,Spanish Restaurant,Clothing Store,Seafood Restaurant
4,Sham Shui Po,深水埗區,"390,600",9.35,"41,529.41",Kowloon,22.328190,114.160854,0,Noodle House,Chinese Restaurant,Italian Restaurant,Snack Place,Café,Shopping Mall,Hong Kong Restaurant,Flea Market,Cha Chaan Teng,Sushi Restaurant
5,Kowloon City,九龍城區,"405,400",10.02,"40,194.70",Kowloon,22.330160,114.189937,1,Thai Restaurant,Dessert Shop,Noodle House,Coffee Shop,Hotpot Restaurant,Café,Halal Restaurant,Restaurant,Dim Sum Restaurant,Pastry Shop
6,Kwun Tong,觀塘區,"641,100",11.27,"56,779.05",Kowloon,22.312937,114.225610,1,Chinese Restaurant,Cha Chaan Teng,Café,Pizza Place,Restaurant,Department Store,Furniture / Home Store,Paper / Office Supplies Store,Shopping Mall,Coffee Shop
7,Wong Tai Sin,黃大仙區,"426,200",9.30,"45,645.16",Kowloon,22.341654,114.193859,1,Park,Fast Food Restaurant,Coffee Shop,Hong Kong Restaurant,Market,Szechuan Restaurant,Burger Joint,Temple,Chinese Restaurant,Pool
8,Yau Tsim Mong,油尖旺區,"318,100",6.99,"44,864.09",Kowloon,22.307404,114.165526,1,Chinese Restaurant,Café,Sandwich Place,Dessert Shop,Indian Restaurant,Shaanxi Restaurant,Market,Park,Clothing Store,Vietnamese Restaurant
9,Islands,離島區,"146,900",175.12,825.14,New Territories,22.262800,113.965500,4,Scenic Lookout,Zoo,Dessert Shop,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant,Flea Market,French Restaurant,Furniture / Home Store
10,Kwai Tsing,葵青區,"507,100",23.34,"21,503.86",New Territories,22.341007,114.104285,3,Tunnel,Chinese Restaurant,Taiwanese Restaurant,Zoo,Gym,Dim Sum Restaurant,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant
11,North,北區,"310,800",136.61,"2,220.19",New Territories,22.500900,114.155800,2,Noodle House,History Museum,Zoo,Gym / Fitness Center,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant,Flea Market,French Restaurant
12,Sai Kung,西貢區,"448,600",129.65,"3,460.08",New Territories,22.382249,114.272828,1,Seafood Restaurant,Café,Thai Restaurant,Burger Joint,Pizza Place,Coffee Shop,Dessert Shop,Park,Gastropub,Chinese Restaurant
13,Sha Tin,沙田區,"648,200",68.71,"9,433.85",New Territories,22.383557,114.189985,1,Dessert Shop,Shopping Mall,Clothing Store,Cantonese Restaurant,Café,Ice Cream Shop,Supermarket,Dumpling Restaurant,Dim Sum Restaurant,Department Store
14,Tai Po,大埔區,"307,100",136.15,"2,220.35",New Territories,22.449402,114.171133,0,Noodle House,Chinese Restaurant,Sushi Restaurant,Bus Stop,Shopping Mall,River,Plaza,Fast Food Restaurant,Coffee Shop,Soup Place
15,Tsuen Wan,荃灣區,"303,600",61.71,"4,887.38",New Territories,22.371661,114.113470,0,Noodle House,Coffee Shop,Dessert Shop,Cha Chaan Teng,Italian Restaurant,Japanese Restaurant,Sushi Restaurant,Buffet,Shopping Mall,Cantonese Restaurant
16,Tuen Mun,屯門區,"495,900",82.89,"5,889.38",New Territories,22.391216,113.976282,1,Coffee Shop,Shopping Mall,Café,Department Store,Cantonese Restaurant,Zoo,Shanghai Restaurant,Seafood Restaurant,Dessert Shop,Steakhouse
17,Yuen Long,元朗區,"607,200",138.46,"4,297.99",New Territories,22.442646,114.030434,0,Chinese Restaurant,Noodle House,Fast Food Restaurant,Dessert Shop,Japanese Restaurant,Market,Hong Kong Restaurant,Sushi Restaurant,Indian Restaurant,Ramen Restaurant

In [130]:
import matplotlib.cm as cm
import matplotlib.colors as colors

In [240]:
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(hk_district_merged['Dist_Lat'], hk_district_merged['Dist_Long'], hk_district_merged['District'], hk_district_merged['Cluster-Labels-']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

In [242]:
hk_district_merged.loc[hk_district_merged['Cluster-Labels-'] == 0, hk_district_merged.columns[[0] + list(range(3, hk_district_merged.shape[1]))]]

,District,Area(km2),Density(/km2),Region,Dist_Lat,Dist_Long,Cluster-Labels-,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
4,Sham Shui Po,9.35,"41,529.41",Kowloon,22.328190,114.160854,0,Noodle House,Chinese Restaurant,Italian Restaurant,Snack Place,Café,Shopping Mall,Hong Kong Restaurant,Flea Market,Cha Chaan Teng,Sushi Restaurant
14,Tai Po,136.15,"2,220.35",New Territories,22.449402,114.171133,0,Noodle House,Chinese Restaurant,Sushi Restaurant,Bus Stop,Shopping Mall,River,Plaza,Fast Food Restaurant,Coffee Shop,Soup Place
15,Tsuen Wan,61.71,"4,887.38",New Territories,22.371661,114.113470,0,Noodle House,Coffee Shop,Dessert Shop,Cha Chaan Teng,Italian Restaurant,Japanese Restaurant,Sushi Restaurant,Buffet,Shopping Mall,Cantonese Restaurant
17,Yuen Long,138.46,"4,297.99",New Territories,22.442646,114.030434,0,Chinese Restaurant,Noodle House,Fast Food Restaurant,Dessert Shop,Japanese Restaurant,Market,Hong Kong Restaurant,Sushi Restaurant,Indian Restaurant,Ramen Restaurant

In [243]:
hk_district_merged.loc[hk_district_merged['Cluster-Labels-'] == 1, hk_district_merged.columns[[0] + list(range(5, hk_district_merged.shape[1]))]]

,District,Region,Dist_Lat,Dist_Long,Cluster-Labels-,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Central and Western,Hong Kong Island,22.281322,114.160258,1,Hotel,Lounge,Cantonese Restaurant,French Restaurant,Chinese Restaurant,Steakhouse,Cycle Studio,Japanese Restaurant,Gym / Fitness Center,Plaza
1,Eastern,Hong Kong Island,22.273400,114.236100,1,Convenience Store,Bakery,Chinese Restaurant,Paper / Office Supplies Store,Tea Room,Coffee Shop,Pharmacy,Cantonese Restaurant,Farmers Market,Furniture / Home Store
3,Wan Chai,Hong Kong Island,22.279015,114.172483,1,Hotel,Coffee Shop,Cantonese Restaurant,Italian Restaurant,Japanese Restaurant,Electronics Store,Chinese Restaurant,Spanish Restaurant,Clothing Store,Seafood Restaurant
5,Kowloon City,Kowloon,22.330160,114.189937,1,Thai Restaurant,Dessert Shop,Noodle House,Coffee Shop,Hotpot Restaurant,Café,Halal Restaurant,Restaurant,Dim Sum Restaurant,Pastry Shop
6,Kwun Tong,Kowloon,22.312937,114.225610,1,Chinese Restaurant,Cha Chaan Teng,Café,Pizza Place,Restaurant,Department Store,Furniture / Home Store,Paper / Office Supplies Store,Shopping Mall,Coffee Shop
7,Wong Tai Sin,Kowloon,22.341654,114.193859,1,Park,Fast Food Restaurant,Coffee Shop,Hong Kong Restaurant,Market,Szechuan Restaurant,Burger Joint,Temple,Chinese Restaurant,Pool
8,Yau Tsim Mong,Kowloon,22.307404,114.165526,1,Chinese Restaurant,Café,Sandwich Place,Dessert Shop,Indian Restaurant,Shaanxi Restaurant,Market,Park,Clothing Store,Vietnamese Restaurant
12,Sai Kung,New Territories,22.382249,114.272828,1,Seafood Restaurant,Café,Thai Restaurant,Burger Joint,Pizza Place,Coffee Shop,Dessert Shop,Park,Gastropub,Chinese Restaurant
13,Sha Tin,New Territories,22.383557,114.189985,1,Dessert Shop,Shopping Mall,Clothing Store,Cantonese Restaurant,Café,Ice Cream Shop,Supermarket,Dumpling Restaurant,Dim Sum Restaurant,Department Store
16,Tuen Mun,New Territories,22.391216,113.976282,1,Coffee Shop,Shopping Mall,Café,Department Store,Cantonese Restaurant,Zoo,Shanghai Restaurant,Seafood Restaurant,Dessert Shop,Steakhouse

In [244]:
hk_district_merged.loc[hk_district_merged['Cluster-Labels-'] == 2, hk_district_merged.columns[[0] + list(range(5, hk_district_merged.shape[1]))]]

,District,Region,Dist_Lat,Dist_Long,Cluster-Labels-,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
11,North,New Territories,22.5009,114.1558,2,Noodle House,History Museum,Zoo,Gym / Fitness Center,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant,Flea Market,French Restaurant

In [221]:
hk_district_merged.loc[hk_district_merged['Cluster-Labels'] == 3, hk_district_merged.columns[[1] + list(range(5, hk_district_merged.shape[1]))]]

,Chinese,Region,Dist_Lat,Dist_Long,Cluster-Labels,Cluster-Labels-3,Cluster-Labels-6,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
10,葵青區,New Territories,22.341007,114.104285,3,0,3,Tunnel,Chinese Restaurant,Taiwanese Restaurant,Zoo,Gym,Dim Sum Restaurant,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant

In [245]:
hk_district_merged.loc[hk_district_merged['Cluster-Labels-'] == 3, hk_district_merged.columns[[1] + list(range(5, hk_district_merged.shape[1]))]]

,Chinese,Region,Dist_Lat,Dist_Long,Cluster-Labels-,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
10,葵青區,New Territories,22.341007,114.104285,3,Tunnel,Chinese Restaurant,Taiwanese Restaurant,Zoo,Gym,Dim Sum Restaurant,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant

In [246]:
hk_district_merged.loc[hk_district_merged['Cluster-Labels-'] == 4, hk_district_merged.columns[[1] + list(range(5, hk_district_merged.shape[1]))]]

,Chinese,Region,Dist_Lat,Dist_Long,Cluster-Labels-,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
9,離島區,New Territories,22.2628,113.9655,4,Scenic Lookout,Zoo,Dessert Shop,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant,Flea Market,French Restaurant,Furniture / Home Store

In [247]:
hk_district_merged.loc[hk_district_merged['Cluster-Labels-'] == 5, hk_district_merged.columns[[1] + list(range(5, hk_district_merged.shape[1]))]]

,Chinese,Region,Dist_Lat,Dist_Long,Cluster-Labels-,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
2,南區,Hong Kong Island,22.2432,114.1974,5,Athletics & Sports,Coffee Shop,Spa,Supermarket,Zoo,German Restaurant,Dumpling Restaurant,Electronics Store,Farmers Market,Fast Food Restaurant